# Generated by Django 5.2.5 on 2025-08-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='funado',
            field=models.BooleanField(),
        ),
    ]
